#!/bin/bash

HOSTS=/etc/backup/hosts
if [ ! -f "$HOSTS" ]; then
    echo Could not find \'$HOSTS\'
    exit
fi

while read HOST; do
  echo $HOST
  DEST=/srv/backup/$HOST/now
  if
   [ ! -d $DEST ]; then
    mkdir -p $DEST
  fi
  rsync \
    --archive \
    --stats \
    --delete-excluded \
    --rsync-path="sudo rsync" \
    $HOST:/srv/backup/local/now/ /srv/backup/$HOST/now
done < $HOSTS
